name: "Build Docs"
on: 
- pull_request
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Sphinx
      run: sudo apt-get update && sudo apt-get install -y python3-sphinx
    - name: Install nox package
      run: pip3 install nox
    - name: Install Sphinx extensions
      run: pip3 install -r doc-req.txt
    - name: Build Sphinx docs
      run: nox -s docs
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./build/docs
        name: docs
    - name: Uninstall Sphinx
      run: sudo dpkg --purge python3-sphinx
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
           name: docs
           path: ${{ github.workspace }}/doc-build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc-build # The folder the action should deploy.
      - name: Delete artifact
        # You may pin to the exact commit or the version.
        # uses: joutvhu/delete-artifact@404b3caf21eaaa38b13c1c7ec45577d07f20223a
        uses: joutvhu/delete-artifact@v1.0.2
        with:
          # The name of the artifact to delete, multiple names can be supplied on new lines.
          name: docs
